In [1]:
#To understand and implement cosine similarity, a metric used to measure the similarity between two vectors

#Task: Write a Python function to calculate the cosine similarity between two vectors.

In [2]:
import numpy as np
from numpy.linalg import norm
 


## array

In [3]:
# define two lists or array
A = np.array([2,1,2,3,2,9])
B = np.array([3,4,2,4,5,5])
 
print("A:", A)
print("B:", B)
 


A: [2 1 2 3 2 9]
B: [3 4 2 4 5 5]


In [4]:
# compute cosine similarity
cosine = np.dot(A,B)/(norm(A)*norm(B))
print("Cosine Similarity:", cosine)

Cosine Similarity: 0.8188504723485274


## matrix

In [5]:
A = np.array([[1,2,2],
               [3,2,2],
               [-2,1,-3]])
B = np.array([[4,2,4],
               [2,-2,5],
               [3,4,-4]])

In [6]:
print("A:\n", A)
print("B:\n", B)
 

A:
 [[ 1  2  2]
 [ 3  2  2]
 [-2  1 -3]]
B:
 [[ 4  2  4]
 [ 2 -2  5]
 [ 3  4 -4]]


In [7]:
cosine = np.sum(A*B, axis=1)/(norm(A, axis=1)*norm(B, axis=1))
 
print("Cosine Similarity:\n", cosine)
print("Cosine Similarity:\n", cosine)

Cosine Similarity:
 [0.88888889 0.5066404  0.41739194]
Cosine Similarity:
 [0.88888889 0.5066404  0.41739194]
