In [1]:
# numpy-for array 

In [2]:
!pip3 install numpy

In [3]:
import numpy as np

In [5]:
lst = [3,45,4,7,78,77]
print(type(lst))
print(lst)

<class 'list'>
[3, 45, 4, 7, 78, 77]


In [6]:
a = np.array([3,45,4,7,78,77])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[ 3 45  4  7 78 77]


In [7]:
tup = (3,45,4,7,78,77)
a = np.array(tup)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[ 3 45  4  7 78 77]


In [13]:
a= np.array([[4,5,8,4],[6,3,2,1],[8,4,2,6]])
print(a)
print(a[1][1])
print(type(a))

[[4 5 8 4]
 [6 3 2 1]
 [8 4 2 6]]
3
<class 'numpy.ndarray'>


# zeros,ones,arrange

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [28]:
np.linspace(0,10,num=3)

array([ 0.,  5., 10.])

In [31]:
arr= [3,5,4,1,9,6,0]
np.sort(arr)

array([0, 1, 3, 4, 5, 6, 9])

In [32]:
a= np.array([4,5,2,3])
b= np.array([8,6,0,1])
np.concatenate((a,b))

array([4, 5, 2, 3, 8, 6, 0, 1])

In [34]:
x= np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [44]:
x= np.array([[1,2],[3,4]])
y=np.array([[5,6]])
print(x)
print("_____________________________")
print(y)
print("_____________________________")
print(y.T)
print("_____________________________")

print(np.concatenate((x,y),axis=0))
print("_____________________________")
print(np.concatenate((x,y.T),axis=1))

[[1 2]
 [3 4]]
_____________________________
[[5 6]]
_____________________________
[[5]
 [6]]
_____________________________
[[1 2]
 [3 4]
 [5 6]]
_____________________________
[[1 2 5]
 [3 4 6]]


In [47]:
x= np.array([[[0,1,2,3,4],
            [5,6,7,8,9]],
           
           [[0,1,2,3,4],
            [5,6,7,8,9]],
            
            [[0,1,2,3,4],
            [5,6,7,8,9]]])
print(x)

[[[0 1 2 3 4]
  [5 6 7 8 9]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]]


In [53]:
x= np.array([[[0,1,2,3,4],
            [5,6,7,8,9]],
           
           [[0,1,2,3,4],
            [5,6,7,8,9]],
            
            [[0,1,2,3,4],
            [5,6,7,8,9]]])
print(x)
x.ndim


[[[0 1 2 3 4]
  [5 6 7 8 9]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]]


3

In [51]:
x.shape


(3, 2, 5)

In [52]:
x.size

30

In [54]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [55]:
b = a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [56]:
b = a.reshape(2,5)
print(b)

ValueError: cannot reshape array of size 6 into shape (2,5)

In [62]:
a=np.array([1,2,3,4,5,6])
a.resize(2,5)
print(a)

[[1 2 3 4 5]
 [6 0 0 0 0]]


# n dimensional array

In [63]:
a=np.array([1,2,3,4,5,6])
print(a)
print(a.shape)
print(a.ndim)

[1 2 3 4 5 6]
(6,)
1


In [64]:
a2=a[np.newaxis,:]
print(a2)
print(a2.shape)
print(a2.ndim)

[[1 2 3 4 5 6]]
(1, 6)
2


In [66]:
a3=a2[np.newaxis,:]
print(a3)
print(a3.shape)
print(a3.ndim)

[[[1 2 3 4 5 6]]]
(1, 1, 6)
3


In [69]:
row_vector=np.array([1,2,3,4,5,6])
row_vector=a[np.newaxis,:]
print(row_vector)
print(row_vector.shape)


[[1 2 3 4 5 6]]
(1, 6)


In [70]:
col_vector=np.array([1,2,3,4,5,6])
col_vector=a[:,np.newaxis]
print(col_vector)
print(col_vector.shape)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


# axis=0 colm 
# axis=1 row


In [71]:
b= np.expand_dims(a,axis=1)
print(b.shape)
print(b.ndim)

(6, 1)
2


In [72]:
c= np.expand_dims(a,axis=0)
print(c.shape)
print(c.ndim)

(1, 6)
2


In [73]:
a=np.array([1,2,3,4,5,6])
print(a[a<5])

[1 2 3 4]


In [76]:
a=np.array([1,2,3,4,5,6])
print(a[a%2==0])

[2 4 6]


# vertical and horizontal stack

In [80]:
a1 = np.array([[1,1],
              [2,2]])

a2 = np.array([[3,3],
              [4,4]])

np.vstack((a1,a2))


array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [81]:
a1 = np.array([[1,2],
              [2,2]])

a2 = np.array([[3,3],
              [4,4]])

np.hstack((a1,a2))


array([[1, 2, 3, 3],
       [2, 2, 4, 4]])

# assignments

In [3]:
#1-Create a NumPy array a with values 1 through 9. Reshape the array to a 3x3 matrix.

import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
b = a.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#2. Create a NumPy array b with values 5 through 13. Reshape the array to a 3x3 matrix.

import numpy as np
a=np.array([5,6,7,8,9,10,11,12,13])
b = a.reshape(3,3)
print(b)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [11]:
#3. Multiply the matrix a by the matrix b using the @ operator

import numpy as np
a = np.array([[1,1],
              [2,2]])

b = np.array([[3,3],
              [4,4]])
s=a@b
print(s)

[[ 7  7]
 [14 14]]


In [12]:
#4. Compute the dot product of the first row of a with the first column of b.

a = np.array([[1,1],
              [2,2]])

b = np.array([[3,3],
              [4,4]])
first_row_a = a[0, :]
first_col_b = b[:, 0]
dot_product_result = np.dot(first_row_a, first_col_b)

print(dot_product_result)


7


In [17]:
#5. Compute the sum of all the elements in the matrix a.
import numpy as np
a=np.array([[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]])
sum1 = np.sum(a)
print(sum1)

126


In [20]:
#6. Compute the product of all the elements in the matrix b.
import numpy as np
b=np.array([[2,3],
           [4,5]])
product = np.prod(b)
print(product)

120


In [22]:
#7. Create a 1D NumPy array c with values [1, 2, 3, 4, 5]. Use the np.insert() function to insert the value 0 at index 2.
import numpy as np
c=[1, 2, 3, 4, 5]
result = np.insert(c,2,0)
print(result)

[1 2 0 3 4 5]


In [24]:
#8. Create a 1D NumPy array d with values [1, 2, 3, 4, 5]. Use the np.delete() function to delete the value at index 3.
import numpy as np
d=[1, 2, 3, 4, 5]
result = np.delete(d,3)
print(result)

[1 2 3 5]


In [28]:
#9. Create a 2D NumPy array e with dimensions 3x4 and values 1 through 12. Use boolean indexing to
#select all elements greater than 5.
import numpy as np
e=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

print(e[e>5])

[ 6  7  8  9 10 11 12]


In [30]:
#10. Create a 2D NumPy array f with dimensions 4x5 and values 1 through 20. Use fancy indexing to
#select the elements at positions (0,0), (1,2), and (2,4)

#select all elements greater than 5.
import numpy as np
f=np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20]])
selected_elements = f[[0, 1, 2], [0, 2, 4]]

print("\nSelected elements at positions (0, 0), (1, 2), and (2, 4):",selected_elements)



Selected elements at positions (0, 0), (1, 2), and (2, 4): [ 1  8 15]


In [44]:
#. Create a 2D NumPy array a with dimensions 5x5 and values 0.5 in the diagonal and 0 elsewhere.
import numpy as np
a = np.zeros((5,5))
np.fill_diagonal(a, 0.5)
print(a)

[[0.5 0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  0.5]]


In [52]:
#12. Create a 3D NumPy array b with dimensions 3x3x3 and random integer values between 0 and 10.
import numpy as np
b = np.random.randint(0, 11, size=(3, 3, 3))
print(b)

[[[4 2 7]
  [1 1 7]
  [2 8 0]]

 [[4 1 0]
  [6 1 5]
  [4 9 3]]

 [[5 1 4]
  [4 5 1]
  [0 8 7]]]


In [55]:
#13. Compute the mean of each row of the matrix b
import numpy as np
import numpy as np
b = np.random.randint(0, 11, size=(3, 3, 3))
mean_of_rows = np.mean(b, axis=2)
print(mean_of_rows)

[[3.         5.33333333 2.66666667]
 [4.66666667 4.33333333 9.33333333]
 [6.33333333 1.66666667 7.33333333]]


In [60]:
#14. Compute the standard deviation of each column of the matrix a.

import numpy as np
b = np.random.randint(0, 11, size=(3,3,3))
sd= np.std(b, axis=1)
print(sd)

[[1.69967317 3.09120617 3.55902608]
 [2.1602469  2.62466929 3.39934634]
 [1.69967317 0.81649658 0.47140452]]


In [62]:
#15. Compute the matrix multiplication of a with its transpose.
import numpy as np
a=np.array([[1,2],
           [3,4]])
a_T=a.T
product=a@a_T
print(product)

[[ 5 11]
 [11 25]]


In [72]:
#16. Create a 2D NumPy array c with dimensions 6x6 and values 1 in the diagonal and 0 elsewhere.
#Use the np.roll() function to shift
#the values in each row to the right by one position.

import numpy as np
c = np.eye(6)
print(c)
c_shifted = np.roll(c, 1, axis=1)
print("\nArray 'c' after shifting each row to the right:")
print(c_shifted)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Array 'c' after shifting each row to the right:
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]]


In [80]:
# 17. Create a 2D NumPy array d with dimensions 4x4 and random values between 0 and 1. 
#Normalize the values in each row to have a sum of 1.
import numpy as np
d = np.random.rand(4,4)
print(d)
normalized_d = d / d.sum(axis=1, keepdims=True)

print("\nNormalized array 'd':")
print(normalized_d)
first_row = sum(normalized_d[0])
print("sumof first raw")
print(first_row)


[[0.95136131 0.78256233 0.77540607 0.87317178]
 [0.47292875 0.02181631 0.77212412 0.17590967]
 [0.18661138 0.10678736 0.51578568 0.95579111]
 [0.12073827 0.46867415 0.93037641 0.06625345]]

Normalized array 'd':
[[0.28125969 0.23135609 0.22924042 0.2581438 ]
 [0.32779019 0.01512103 0.53516457 0.12192421]
 [0.10573029 0.06050359 0.2922339  0.54153221]
 [0.07612551 0.29549915 0.58660253 0.04177282]]
sumof first raw
1.0


In [89]:
#18. Create a 2D NumPy array e with dimensions 3x3 and values 1 through 9.
#Use the np.flipud() function to flip the matrix vertically.
import numpy as np
d = np.arange(1, 10).reshape(3, 3)
print(d)
d_flipped = np.flipud(d)
print(d_flipped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
