In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
data =  pd.read_csv("headbrain.csv")
data.head()

Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0       1          1             4512                 1530
1       1          1             3738                 1297
2       1          1             4261                 1335
3       1          1             3777                 1282
4       1          1             4177                 1590

In [3]:
data.shape

(237, 4)

In [4]:
data.columns

Index(['Gender', 'Age Range', 'Head Size(cm^3)', 'Brain Weight(grams)'], dtype='object')

In [5]:
#collecting x and y
x=data['Head Size(cm^3)'].values
y=data['Brain Weight(grams)'].values

In [6]:
x

array([4512, 3738, 4261, 3777, 4177, 3585, 3785, 3559, 3613, 3982, 3443,
       3993, 3640, 4208, 3832, 3876, 3497, 3466, 3095, 4424, 3878, 4046,
       3804, 3710, 4747, 4423, 4036, 4022, 3454, 4175, 3787, 3796, 4103,
       4161, 4158, 3814, 3527, 3748, 3334, 3492, 3962, 3505, 4315, 3804,
       3863, 4034, 4308, 3165, 3641, 3644, 3891, 3793, 4270, 4063, 4012,
       3458, 3890, 4166, 3935, 3669, 3866, 3393, 4442, 4253, 3727, 3329,
       3415, 3372, 4430, 4381, 4008, 3858, 4121, 4057, 3824, 3394, 3558,
       3362, 3930, 3835, 3830, 3856, 3249, 3577, 3933, 3850, 3309, 3406,
       3506, 3907, 4160, 3318, 3662, 3899, 3700, 3779, 3473, 3490, 3654,
       3478, 3495, 3834, 3876, 3661, 3618, 3648, 4032, 3399, 3916, 4430,
       3695, 3524, 3571, 3594, 3383, 3499, 3589, 3900, 4114, 3937, 3399,
       4200, 4488, 3614, 4051, 3782, 3391, 3124, 4053, 3582, 3666, 3532,
       4046, 3667, 2857, 3436, 3791, 3302, 3104, 3171, 3572, 3530, 3175,
       3438, 3903, 3899, 3401, 3267, 3451, 3090, 34

In [7]:
x.ndim

1

In [8]:
#mean x and y
mean_x=np.mean(x)
mean_y=np.mean(y)

In [9]:
mean_x

3633.9915611814345

In [10]:
mean_y

1282.873417721519

In [11]:
n=len(x)

In [12]:
n

237

In [13]:
x=x.reshape(n,1)

In [14]:
x.ndim

2

In [15]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

In [16]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train,y_train)

y_predicted = model.predict(X_test)

In [17]:
#calculating R2 score

r2_score = model.score(x,y)
print(r2_score)

0.6382773111381818


In [18]:
model.coef_

array([0.26291756])

In [19]:
model.intercept_

323.5755012009116

In [20]:
model.predict([[4261]])

array([1443.8672091])

In [21]:
model.predict(X_test)

array([1306.88716221, 1219.07269836, 1243.52403111, 1318.71845225,
       1323.71388582, 1217.23227547, 1185.6821687 , 1274.81122033,
       1306.3613271 , 1288.2200157 , 1391.80953293, 1217.75811058,
       1261.13950739, 1421.25629925, 1195.9359534 , 1109.43607734,
       1358.15608571, 1317.14094691, 1236.68817464, 1038.71125466,
       1319.24428736, 1197.25054118, 1252.20031047, 1297.15921262,
       1227.48606017, 1262.45409517, 1231.69274107, 1388.65452225,
       1185.15633359, 1402.32623519, 1133.88741008, 1297.42213018,
       1302.68048131, 1305.57257443, 1287.69418059, 1326.34306138,
       1365.25485973, 1244.57570134, 1387.33993447, 1153.34330926,
       1357.6302506 , 1441.76386865, 1200.1426343 , 1316.6151118 ,
       1296.37045995, 1342.64394988, 1213.02559457, 1177.53172445])